---
# Managing Epoptes installation on 'docenti' role.

- name: Configuring the Epoptes server
  lineinfile:
    dest: /etc/default/epoptes
    line: 'SOCKET_GROUP="{{ ansible_local.domain.domainshort }}\docenti"'
    state: present

- name: Stopping epoptes SysV daemon
  shell: /etc/init.d/epoptes stop
  ignore_errors: yes

- name: Disabling sysv start
  shell: /usr/sbin/update-rc.d -f epoptes remove

- name: Installing upstart service
  copy:
    src: epoptes.conf
    dest: /etc/init/epoptes.conf
    owner: root
    group: root
    mode: 0644

- name: Verify epoptes status
  shell: /sbin/status epoptes
  register: epoptes_status

- name: Starting epoptes from upstart
  shell: /sbin/start epoptes
  when:  epoptes_status.stdout.find("start/running") == -1
