---
- name: Removing upgrade-notification from /etc
  lineinfile:
    dest: /etc/update-manager/release-upgrades
    line: "Prompt=never"
    regexp: '^Prompt='
    state: present

- name: Removing notifications for system upgrade
  shell: >
    test -f /usr/share/upstart/sessions/update-notifier-release.conf && mv /usr/share/upstart/sessions/update-notifier-release.conf /usr/share/upstart/sessions/update-notifier-release.conf.disabled
  ignore_errors: yes
