---
- name: Permetto ai domadmins di usare sudo
  template: src=sudoers.d dest=/etc/sudoers.d/domadmins owner=root group=root mode=0440
  sudo: yes

- name: verifica join a dominio
  shell: wbinfo -t
  sudo: yes
  register: check_domain
  changed_when: check_domain.rc != 0
  ignore_errors: yes

- name: Join a dominio
  shell: net rpc join -U admin%{{ domainadminpasswd }}
  sudo: yes
  when: check_domain|changed
  register: domainjoin
  notify:
    - reboot
