---
# Configurazioni per messa in dominio.
# Impostazioni grafiche da gestire in dominio

- include: ntp.yml
  tags:
    - domain
    - ntp

- include: nss.yml
  tags:
    - domain
    - nss

- include: gui-changes.yml
  tags:
    - domain
    - gui
