---
# PAM_mount configuration

- name: Installing pam_mount
  apt:
    name: libpam-mount
    state: present

- name: Configuring pam_mount
  template:
    src: pam_mount.conf.xml
    dest: /etc/security/pam_mount.conf.xml
    backup: yes
