---
# Configurazione base per pam_mount

- name: Installazione pam_mount
  apt: name=libpam-mount state=present
  sudo: yes

- name: Configurazione di pam_mount
  template: src=pam_mount.conf.xml dest=/etc/security/pam_mount.conf.xml backup=yes
  sudo: yes
