---

- name: Configuring sudo to accept users other than local admin
  copy:
    src: polkit-1.txt
    dest: /etc/polkit-1/localauthority.conf.d/51-ubuntu-admin.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  sudo: yes
