---
# Adjusting system for domain proxy certificate

- name: Creating needed directories
  file:
    path: '{{ item }}'
    mode: 0755
    state: directory
  with_items:
    - /usr/lib/firefox/browser/defaults/profile
    - /usr/local/share/ca-certificates/{{ domainfull }}

- name: Getting SSL transparent proxy certificate
  get_url:
    url: 'http://{{ serverfqdn }}/proxy.crt'
    dest: /usr/local/share/ca-certificates/{{ domainfull }}/ca.crt 
  register: proxycrt_dwnl

- name: Adding certificate sto the ones used by the system
  shell: update-ca-certificates
  when: proxycrt_dwnl|changed
  sudo: yes

- name: Firefox settings to include certificate
  get_url:
    url: 'http://{{ serverfqdn }}/ks/cert8.db'
    dest: /usr/lib/firefox/browser/defaults/profile
