---
- name: Verifico presenza di directory necessarie
  file:
    path: '{{ item }}'
    mode: 0755
    state: directory
  with_items:
    - /usr/lib/firefox/browser/defaults/profile
    - /usr/local/share/ca-certificates/{{ domainfull }}
  sudo: yes

- name: Scarico il certificato client per proxy trasparente SSL
  get_url:
    url: http://{{ serverfqdn }}/proxy.crt
    dest: /usr/local/share/ca-certificates/{{ domainfull }}/ca.crt 
  sudo: yes
  register: proxycrt_dwnl

- name: Aggiungo il certificato a quelli utilizzati dal sistema
  shell: update-ca-certificates
  when: proxycrt_dwnl|changed
  sudo: yes

- name: Scarico il database dei certificati di FF con certificato server aggiornato.
  get_url:
    url: 'http://{{ serverfqdn }}/ks/cert8.db'
    dest: /usr/lib/firefox/browser/defaults/profile
  sudo: yes
