---
# Adjusting system for domain proxy certificate

- name: Creating needed directories
  file:
    path: '{{ item }}'
    mode: 0755
    state: directory
  with_items:
    - '/usr/lib/firefox/browser/defaults/profile'
    - '/usr/local/share/ca-certificates/{{ ansible_local.domain.domainfull }}'

- name: Getting SSL transparent proxy certificate
  get_url:
    url: 'http://{{ ansible_local.domain.serverfqdn }}/proxy.crt'
    dest: '/usr/local/share/ca-certificates/{{ ansible_local.domain.domainfull }}/ca.crt'
  register: proxycrt_dwnl

- name: Adding certificates to the ones used by the system
  shell: update-ca-certificates
  when: proxycrt_dwnl|changed

- name: Firefox settings to include certificate
  get_url:
    url: 'http://{{ ansible_local.domain.serverfqdn }}/ks/server-ca/cert8.db'
    dest: /usr/lib/firefox/browser/defaults/profile/cert8.db
