---
# Managing installation/deletion of packages set with NetworkPackageManager
# within NethServer console

- name: Updating package cache.
  apt: update_cache=yes cache_valid_time=180
  become: yes

- name: Debug
  debug: var=ansible_local.noderole.addpkg

- name: Installing packages for specific role from NetworkPackageManager
  apt:
    name: '{{ item }}'
    state: present
  with_items: "{{ ansible_local.noderole.addpkg }}"
  when: ansible_local.noderole.addpkg is defined and ansible_local.noderole.addpkg|join(' ')|trim != ''
  become: yes

- name: Removing packages for specific role from NetworkPackageManager
  apt:
    name: '{{ item }}'
    state: absent
    purge: yes
  with_items: "{{ ansible_local.noderole.delpkg }}"
  when: ansible_local.noderole.delpkg is defined and ansible_local.noderole.delpkg|join(' ')|trim != ''
  become: yes

- name: Updating local hash for packages
  shell: 'rm -f {{ ansible_local.checksum.pkgver_file }} && echo "{{ ansible_local.checksum.pkgver }}" > {{ ansible_local.checksum.pkgver_file }}'
