---

- name: Ensure needed packages are installed
  apt:
    name: "{{ item }}"
    state: present
  sudo: yes
  with_items:
    - unattended-upgrades
    - update-notifier-common

- name: Configuring unattended upgrades from file
  copy:
    src: 50-unattended-upgrades
    dest: /etc/apt/apt.conf.d/50-unattended-upgrades

- name: Activating automatic updates
  copy:
    src: 20-auto-upgrades
    dest: /etc/apt/apt.conf.d/20-auto-upgrades
