---
# Fixing all the stuff around repositories.

# Provide a clean and ordered sources.list
- name: Change main repositories
  get_url:
    url: "http://{{ ansible_local.domain.serverfqdn }}/ks/repoconfig/sources.list"
    dest: /etc/apt/sources.list

- name: Adding additional repositories
  get_url:
    url: "http://{{ ansible_local.domain.serverfqdn }}/ks/repoconfig/{{ item }}"
    dest: "/etc/apt/sources.list.d/{{ item }}"
  with_items:
    - ansible-ansible-trusty.list
    - libreoffice-ppa-trusty.list
    - bglug-trusty.list

- name: Updating package database
  apt: update_cache=yes
