---
# Configurazione di base del sistema.

- name: Cambiamento apt/sources.list
  template:
    src: apt/sources.list
    dest: /etc/apt/sources.list
    backup: yes
  when: ansible_product_name != "VirtualBox"

- name: Aggiornamento pacchetti disponibili
  apt: update_cache=yes
  sudo: yes

- name: Verifica desktop Edubuntu
  shell: 'tasksel --list-tasks | grep "^i edubuntu-desktop-gnome"'
  ignore_errors: yes
  register: check_edubuntu_desktop
  changed_when: check_edubuntu_desktop.rc != 0
  sudo: yes

- name: Installazione desktop environment
  shell: 'tasksel install edubuntu-desktop-gnome'
  when: checked_edubuntu_desktop|changed
  sudo: yes

- name: Installazione pacchetti aggiuntivi
  apt: pkg={{ item }} state=installed
  with_items:
    - ubuntu-edu-secondary
    - epoptes-client
  sudo: yes

- name: Rimozione di pacchetti non richiesti
  apt: pkg={{ item }} state=absent purge=yes
  with_items:
    - unity-webapps-common
    - zeitgeist-core
    - zeitgeist-datahub
    - epoptes
  sudo: yes

  #- name: Correggo NetworkManager per gestire la rete
  #  lineinfile:
  #    dest: /etc/NetworkManager/NetworkManager.conf
  #    regexp: '^managed=false'
  #    line: 'managed=true'
  #    state: present

# Configura networkmanager
