---

- name: Correggo NetworkManager per gestire la rete
  lineinfile:
    dest: /etc/network/interfaces
    regexp: "{{ item }}"
    state: absent
  with_items:
    - ^auto eth0
    - ^iface eth0

- name: Riavvio servizio NetworkManager
  service: name=network-manager state=restarted

- name: Cambio greeter di default
  lineinfile:
    dest: /usr/share/lightdm/lightdm.conf.d/50-ubuntu.conf
    regexp: "^user-session=ubuntu$"
    line: "user-session=gnome-fallback"
