---
# Manages the installation of the main desktop environment

- name: Checking for desktop environment
  shell: 'tasksel --list-tasks | grep "^i edubuntu-desktop-gnome"'
  ignore_errors: yes
  register: check_edubuntu_pkg
  changed_when: check_edubuntu_pkg.rc != 0
  tags: edu-install
  sudo: yes

- name: Installation of the desktop environment
  shell: "DEBIAN_FRONTEND=noninteractive /usr/bin/apt-get -y install edubuntu-desktop-gnome^"
  when: check_edubuntu_pkg|changed
  tags: edu-install
  sudo: yes

- name: Change default desktop environment
  replace:
    dest: /usr/share/lightdm/lightdm.conf.d/50-ubuntu.conf
    regexp: "^user-session=ubuntu$"
    replace: "user-session=gnome-fallback"
