---
# Configurazioni di base.
# Al termine delle configurazioni di base, avremo un'installazione
# completa di Edubuntu.

- include: base.yml
  tags:
    - base
    - edubuntu

- include: role.yml
  tags:
    - base
    - role
